#! /bin/sh
PATH="/usr/bin:/bin:/usr/sbin:/sbin"

TARGET=$2
cd "${TARGET}"

#Rebuild the kext cache
if [ -f ./Library/Extensions.kextcache ]; then
	rm ./Library/Extensions.kextcache
fi
kextcache -k ./Library/Extensions
